# Generated by Django 5.1.15 on 2026-10-03 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Auth"),
                            ("database", "Database"),
                            ("frontend", "Frontend"),
                            ("api", "API"),
                            ("devops", "DevOps"),
                            ("testing", "Testing"),
                            ("security", "Security"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnalyzeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=120)),
                ("files_count", models.PositiveIntegerField(default=0)),
                ("concepts_found", models.PositiveIntegerField(default=0)),
                ("cards_returned", models.PositiveIntegerField(default=0)),
                ("llm_calls", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("mode", models.CharField(default="live", max_length=10)),
                ("outcome", models.CharField(default="ok", max_length=40)),
                ("trace", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyze_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("why_here", models.TextField()),
                ("diagram_mermaid", models.TextField(blank=True)),
                ("doc_url", models.URLField(blank=True, max_length=500)),
                ("doc_verified", models.BooleanField(default=False)),
                ("code_snippet", models.TextField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("saved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="core.concept",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_token_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        blank=True,
                        help_text="First characters of the token, for display only",
                        max_length=16,
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("daily_card_limit", models.PositiveIntegerField(default=8)),
                ("must_change_password", models.BooleanField(default=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("period_days", models.PositiveIntegerField(default=7)),
                ("title", models.CharField(max_length=200)),
                ("body_markdown", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("mode", models.CharField(default="live", max_length=10)),
                ("trace", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("seen", "Seen"),
                            ("known", "Known"),
                            ("muted", "Muted"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("seen_count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("known_at", models.DateTimeField(blank=True, null=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_concepts",
                        to="core.concept",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_concepts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "concept"), name="unique_user_concept"
                    )
                ],
            },
        ),
    ]
