# Generated by Django 5.1.15 on 2026-10-03 13:34

from django.db import migrations, models
from django.db.models import F


def mark_existing_delivered(apps, schema_editor):
    apps.get_model("core", "Card").objects.update(delivered_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_delivered, migrations.RunPython.noop),
    ]
