# Generated by Django 5.1.15 on 2026-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='analogy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pitfall',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='explanation_depth',
            field=models.CharField(choices=[('brief', 'Brief'), ('standard', 'Standard'), ('deep', 'Deep dive')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_diagrams',
            field=models.BooleanField(default=True, help_text='Add a small diagram when a concept has a flow or relationship'),
        ),
        migrations.AddField(
            model_name='profile',
            name='terminal_detail',
            field=models.CharField(choices=[('compact', 'Compact'), ('visual', 'With flow + pitfall'), ('link', 'Just a link')], default='compact', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_analogies',
            field=models.BooleanField(default=True, help_text='Add a one-line everyday comparison'),
        ),
    ]
