# Generated by Django 5.1.15 on 2026-10-03 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_card_style_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userconcept",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ComprehensionCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("key_points", models.JSONField(blank=True, default=list)),
                ("time_limit_seconds", models.PositiveIntegerField(default=240)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("answer", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("passed", "Passed"),
                            ("partial", "Almost"),
                            ("failed", "Not yet"),
                            ("unverified", "Couldn't verify"),
                            ("expired", "Time ran out"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("rubric", models.JSONField(blank=True, default=dict)),
                ("feedback", models.TextField(blank=True)),
                ("missed_points", models.JSONField(blank=True, default=list)),
                (
                    "integrity",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("review", "Review"),
                            ("flagged", "Flagged"),
                        ],
                        default="clean",
                        max_length=10,
                    ),
                ),
                ("suspicion", models.PositiveIntegerField(default=0)),
                ("integrity_signals", models.JSONField(blank=True, default=list)),
                ("telemetry", models.JSONField(blank=True, default=dict)),
                ("mode", models.CharField(default="live", max_length=10)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="core.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
